services:
  - type: web
    name: planwise-backend
    env: python
    rootDir: server
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'import sys; print(f\"Python version: {sys.version}\")' && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 app:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: planwise-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://planwise-phase4-project-frontend.vercel.app

databases:
  - name: planwise-db
    databaseName: planwise
    user: planwise